---
    version: "2.4"
    services:
      wallpaperwatcher:
        image: wallpaperwatcher:0.0.2
        build:
          context: .
        volumes:
          - ./wallpaper_config.yaml:/app/wallpaper_config.yaml
          - ./auth_info.yaml:/app/auth_info.yaml
          - ./images/:/app/images/
          - hashdb:/app/data/
    volumes:
      hashdb:
