---
subreddits:
    moescape:
        folder: moescape
    awwnime:
        folder: awwnime

target_size:
#    width: 3440
#    height: 1440
    width: 1920
    height: 1080
aspect_ratio_tolerance: 0.01
max_downloads: 5
update_interval: 60000
